# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56fcb1a536355ef6764de47a34a2a989aabfb966d6c3196656537556f658d1b4473fa5b98609e32e3b3e7da9363ce532a70687cf396bf5ef2b7f4228935247a
  email_id: center24enquiry@gmail.com 
  email_password: ratnamraj
  sender_link: http://localhost:3000/reply/
  listener_link: http://localhost:3000/response/
  default_password: 12345678

test:
  secret_key_base: 9432053b19e2230d6f451a8574eff5b93d6dd38757982f05c43d6c7a8ee9210c6cac9d93f182223ddc353b0611874045235e7ad0a646fb0c0f32bb6e61ba3a21
  email_id: center24enquiry@gmail.com
  email_password: ratnamraj
  sender_link: http://localhost:3000/reply/
  default_password: 12345678
  listener_link: http://localhost:3000/response/

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: 9432053b19e2230d6f451a8574eff5b93d6dd38757982f05c43d6c7a8ee9210c6cac9d93f182223ddc353b0611874045235e7ad0a646fb0c0f32bb6e61ba3a21
  email_id: center24enquiry@gmail.com
  email_password: ratnamraj
  sender_link: https://ques-era.herokuapp.com/reply/
  default_password: 12345678
  listener_link: https://ques-era.herokuapp.com/response/

  